name: Create Release

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release
      id: release
      uses: googleapis/release-please-action@v4
      with:
        path: "."
        token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
